<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>
<script type="module" src="https://adobecommerce-dev.dev.logik.io/ui/wc-build/logik-wc.es.js"></script>
<div class="logik-configurator" data-bind="scope: 'logik-configurator'">
    <h2 class="logik-configurator-title">Logik Configurator</h2>
    <div class="logik-configurator-content">
        <p>Current Cart ID: <span data-bind="text: cartId"></span></p>
    </div>
</div>
<script type="text/x-magento-init">
{
    ".logik-configurator": {
        "Magento_Ui/js/core/app": {
            "components": {
                "logik-configurator": {
                    "component": "Logik_Integration/js/logik-configurator"
                }
            }
        }
    }
}
</script>